"""Configuration constants for text2speech."""

# API Keys
MIN_API_KEY_LENGTH = 10
LEGACY_API_KEY_LENGTH = 32
API_KEY_PREFIX = "sk_"

# Audio Settings
MIN_SPEED = 0.5
MAX_SPEED = 2.0
DEFAULT_SPEED = 1.0

MIN_VOLUME = 0.0
MAX_VOLUME = 1.0
DEFAULT_VOLUME = 0.8

# Queue Settings
MAX_RECENT_MESSAGES = 100
DEFAULT_QUEUE_SIZE = 50
DEFAULT_DUPLICATE_TIMEOUT = 2.0
QUEUE_POLL_INTERVAL = 0.1

# Sample Rates
KOKORO_SAMPLE_RATE = 24000
DEFAULT_SAMPLE_RATE = 24000
